name: Build Godot Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential scons pkg-config \
            libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev \
            libglu1-mesa-dev libasound2-dev libpulse-dev libudev-dev \
            libxi-dev libxrandr-dev libwayland-dev wayland-protocols \
            libxkbcommon-dev libdbus-1-dev clang python3 python3-pip \
            openjdk-17-jdk unzip

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android Editor
        run: |
          scons platform=android target=release_debug android_arch=arm64v8 -j4
          ls -lh bin/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Godot-Android
          path: bin/*.apk
